# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-05 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Orden')),
                ('block', multiselectfield.db.fields.MultiSelectField(choices=[(b'home-imagen-1', b'Home: imagen 1'), (b'home-imagen-2', b'Home: imagen 2'), (b'home-imagen-3', b'Home: imagen 3')], max_length=1000, verbose_name='block')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='title')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='location')),
                ('highlight_body', models.TextField(blank=True, null=True, verbose_name='text')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('link_target', models.CharField(blank=True, choices=[(b'', b''), (b'_self', 'Current window'), (b'_blank', 'New window')], max_length=15, null=True, verbose_name='link target ')),
                ('file', models.FileField(blank=True, upload_to=b'highlights/highlight_files/', verbose_name='file')),
                ('mobile_file', models.FileField(blank=True, upload_to=b'highlights/highlight_mobile_files/', verbose_name='mobile file')),
                ('extra_file', models.FileField(blank=True, null=True, upload_to=b'highlights/highlight_files/', verbose_name='extra file')),
                ('file_caption', models.TextField(blank=True, null=True, verbose_name='file caption')),
                ('video', models.CharField(blank=True, max_length=400, null=True, verbose_name='video')),
                ('is_sticky', models.BooleanField(db_index=True, default=False, verbose_name='is sticky?')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='visible')),
                ('login_required', models.BooleanField(db_index=True, default=False, verbose_name='login required?')),
                ('pub_date', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='publication date')),
                ('pub_end_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='publication end date')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='creation date')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'highlight',
                'verbose_name_plural': 'highlights',
            },
        ),
    ]
