# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-03 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'highlights/banners', verbose_name='Imagen')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible?')),
            ],
        ),
    ]
