# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-15 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0003_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to=b'highlights/banners', validators=[utils.validators.validate_object_size], verbose_name='Imagen'),
        ),
    ]
