# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-08-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0004_auto_20190115_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='block',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'home-imagen-1', b'Home: imagen 1'), (b'home-imagen-2', b'Home: imagen 2'), (b'home-imagen-3', b'Home: imagen 3'), (b'home-popup-desktop', b'Home: Popup Desktop'), (b'home-popup-mobile', b'Home: Popup - Mobile')], max_length=1000, verbose_name='block'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='video',
            field=models.CharField(blank=True, help_text=b'Utilizar un iframe para mostrar un video', max_length=400, null=True, verbose_name='video'),
        ),
    ]
