# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-09-30 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0005_auto_20190827_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='banner',
            name='link_target',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'_self', 'Current window'), (b'_blank', 'New window')], max_length=15, null=True, verbose_name='link target '),
        ),
    ]
