# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-11-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0006_auto_20190930_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='sub_title',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='sub_title'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='block',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'home-principal', b'Home: principal'), (b'home-imagen-1', b'Home: imagen 1'), (b'home-imagen-2', b'Home: imagen 2'), (b'home-imagen-3', b'Home: imagen 3'), (b'home-imagen-4', b'Home: imagen 4'), (b'home-popup-desktop', b'Home: Popup Desktop'), (b'home-popup-mobile', b'Home: Popup - Mobile')], max_length=1000, verbose_name='block'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='title',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='title'),
        ),
    ]
